apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server-deployment
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message
        image: tonnytg/node-app:latest
        ports:
          - name: http
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  