apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort 
  selector:
    app.kubernetes.io/instance: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080