apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins-project
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.jenkins.volume.pvc.storage }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/